-- AdminPanel: tablas, funciones y policies

-- Admin whitelist (por email)
create table if not exists admin_whitelist (
  email text primary key
);

-- Función para comprobar admin por email en el JWT
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists(
    select 1
    from admin_whitelist
    where email = (auth.jwt() ->> 'email')
  );
$$;

-- Perfiles de usuario básicos (para gestión admin y bloqueo)
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  created_at timestamptz default now(),
  is_blocked boolean default false,
  last_seen timestamptz
);

alter table public.user_profiles enable row level security;

drop policy if exists "User can read own profile" on public.user_profiles;
drop policy if exists "User can update own profile" on public.user_profiles;
drop policy if exists "Admin full access to profiles" on public.user_profiles;

create policy "User can read own profile"
  on public.user_profiles for select
  using (auth.uid() = user_id);

create policy "User can update own profile"
  on public.user_profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Admin full access to profiles"
  on public.user_profiles for all
  using (public.is_admin())
  with check (public.is_admin());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.user_profiles (user_id, email, created_at)
  values (new.id, new.email, now())
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Mantenimiento avanzado: whitelist + mensaje
create table if not exists public.maintenance_whitelist (
  email text primary key
);

alter table public.maintenance_whitelist enable row level security;
drop policy if exists "Admin manage maintenance whitelist" on public.maintenance_whitelist;
create policy "Admin manage maintenance whitelist"
  on public.maintenance_whitelist for all
  using (public.is_admin())
  with check (public.is_admin());

create table if not exists public.app_settings_text (
  key text primary key,
  value text
);

alter table public.app_settings_text enable row level security;
drop policy if exists "Admin manage app_settings_text" on public.app_settings_text;
drop policy if exists "Public read app_settings_text" on public.app_settings_text;
create policy "Admin manage app_settings_text"
  on public.app_settings_text for all
  using (public.is_admin())
  with check (public.is_admin());
create policy "Public read app_settings_text"
  on public.app_settings_text for select
  using (true);

create or replace function public.is_maintenance_whitelisted(p_email text)
returns boolean
language sql
stable
as $$
  select exists(
    select 1 from maintenance_whitelist where email = p_email
  );
$$;

-- Notificaciones programadas
create table if not exists public.scheduled_notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  body text not null,
  language text,
  min_version text,
  max_version text,
  url text,
  send_at timestamptz not null,
  status text default 'pending',
  created_by uuid
);

alter table public.scheduled_notifications enable row level security;
drop policy if exists "Admin manage scheduled_notifications" on public.scheduled_notifications;
create policy "Admin manage scheduled_notifications"
  on public.scheduled_notifications for all
  using (public.is_admin())
  with check (public.is_admin());

-- Reportes de bugs y mejoras
create table if not exists public.feedback_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.user_profiles(user_id) on delete set null,
  type text not null,
  title text,
  message text not null,
  screenshot_url text,
  status text default 'open',
  created_at timestamptz default now()
);

alter table public.feedback_reports
  add column if not exists screenshot_url text;

alter table public.feedback_reports enable row level security;

drop policy if exists "Admin manage feedback_reports" on public.feedback_reports;
drop policy if exists "Users create feedback_reports" on public.feedback_reports;

create policy "Admin manage feedback_reports"
  on public.feedback_reports for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Users create feedback_reports"
  on public.feedback_reports for insert
  with check (auth.uid() = user_id);

-- Push subscriptions: idioma y versión (para segmentación)
alter table public.push_subscriptions
  add column if not exists language text;

alter table public.push_subscriptions
  add column if not exists app_version text;

-- RPCs de administración
create or replace function public.get_admin_users()
returns table (
  user_id uuid,
  email text,
  created_at timestamptz,
  is_blocked boolean,
  last_seen timestamptz
)
language sql
security definer
as $$
  select user_id, email, created_at, is_blocked, last_seen
  from public.user_profiles
  order by created_at desc;
$$;

create or replace function public.set_user_blocked(p_user_id uuid, p_blocked boolean)
returns void
language sql
security definer
as $$
  update public.user_profiles set is_blocked = p_blocked where user_id = p_user_id;
$$;

create or replace function public.delete_user_data(p_user_id uuid)
returns void
language plpgsql
security definer
as $$
begin
  delete from public.daily_logs where user_id = p_user_id;
  delete from public.habits where user_id = p_user_id;
  delete from public.push_subscriptions where user_id = p_user_id;
  delete from public.user_profiles where user_id = p_user_id;
end;
$$;

create or replace function public.get_admin_habit_stats()
returns table (
  habit_id bigint,
  title text,
  completed bigint,
  skipped bigint
)
language sql
security definer
as $$
  select h.id as habit_id,
         h.title as title,
         sum(case when l.status = 'completed' then 1 else 0 end) as completed,
         sum(case when l.status = 'skipped' then 1 else 0 end) as skipped
  from public.habits h
  left join public.daily_logs l on l.habit_id = h.id
  group by h.id, h.title
  order by completed desc;
$$;

create or replace function public.get_admin_app_metrics()
returns table (
  dau bigint,
  wau bigint,
  mau bigint,
  avg_completion numeric,
  avg_habits_per_user numeric
)
language sql
security definer
as $$
  with logs as (
    select user_id, status, created_at
    from public.daily_logs
  ),
  users as (
    select distinct user_id from logs
  ),
  total_users as (
    select count(*)::numeric as cnt from public.user_profiles
  ),
  totals as (
    select
      count(*)::numeric as total_logs,
      sum(case when status = 'completed' then 1 else 0 end)::numeric as total_completed
    from logs
  )
  select
    (select count(distinct user_id) from logs where created_at >= now() - interval '1 day') as dau,
    (select count(distinct user_id) from logs where created_at >= now() - interval '7 days') as wau,
    (select count(distinct user_id) from logs where created_at >= now() - interval '30 days') as mau,
    case when (select total_logs from totals) = 0 then 0 else (select total_completed from totals) / (select total_logs from totals) end as avg_completion,
    case when (select cnt from total_users) = 0 then 0 else (select count(*)::numeric from public.habits) / (select cnt from total_users) end as avg_habits_per_user;
$$;

drop function if exists public.get_admin_feedback();
create or replace function public.get_admin_feedback()
returns table (
  id uuid,
  user_id uuid,
  user_email text,
  user_full_name text,
  type text,
  title text,
  message text,
  screenshot_url text,
  status text,
  created_at timestamptz
)
language sql
security definer
as $$
  select
    f.id,
    f.user_id,
    p.email as user_email,
    p.full_name as user_full_name,
    f.type,
    f.title,
    f.message,
    f.screenshot_url,
    f.status,
    f.created_at
  from public.feedback_reports f
  left join public.user_profiles p on p.user_id = f.user_id
  order by
    case when f.status = 'open' then 0 else 1 end,
    f.created_at desc;
$$;

create or replace function public.get_admin_user_ids()
returns table (
  user_id uuid
)
language sql
security definer
as $$
  select p.user_id
  from public.user_profiles p
  join public.admin_whitelist w on lower(w.email) = lower(p.email);
$$;
